Update korbo translations
SkautDevs/kissj pull request #176
Opened 2022-06-27 20:26 UTC by MistrKernnunos

2022-06-27 20:58 UTC, tomtomklima requested changes

2022-06-27 20:58 UTC, tomtomklima commented on src/Event/EventType/Korbo/cs.yaml
> +        successfullySent: "Úspěšně jsi poslal/a svou přihlášku na KORBO 2022. Nyní musíme zkontrolovat, zda je všechno v pořádku, a pokud je, pošleme ti platební údaje. Mohlo by to trvat i několik dn
Je nutné rušit dynamičnost? Takhle to nepůjde použít pro další ročníky

2022-06-28 20:00 UTC, tomtomklima commented on src/Event/EventType/Korbo/cs.yaml
> +        successfullySent: "Úspěšně jsi poslal/a svou přihlášku na KORBO 2022. Nyní musíme zkontrolovat, zda je všechno v pořádku, a pokud je, pošleme ti platební údaje. Mohlo by to trvat i několik dn
Čitelné v template, nebo pro účastníka? Zauvažuj ještě nad tou změnou. Jestli je cílem používat všude kapitálky, pojďme do toho všude nastavením v DB

2022-07-13 08:34 UTC, closed without merging

2022-07-13 09:26 UTC, tomtomklima commented
@MistrKernnunos co to typo, co tam máme, nebudeme řešit?

2022-07-13 09:59 UTC, MistrKernnunos commented
Nakonec update překladů provedl Lung, takže už tenhle PR není potřeba. A to typo co tohle opravuje už tam není.