New attributes for participant: mental health, medicaments and printed-handbook
SkautDevs/kissj pull request #227
Opened 2023-11-27 17:26 UTC by paaton

Adds 3 new attributes for participant, including mental health, medicaments and printed-handbook yes/no.

2023-11-28 17:37 UTC, tomtomklima requested changes

2023-11-28 17:37 UTC, tomtomklima commented on sql/init-postgresql.sql
> +	medicaments TEXT,
není potřeba, úvodní load obstarají migrace

2023-11-28 17:37 UTC, tomtomklima commented on sql/init.sql
> +	medicaments 			   TEXT,
stejné, není potřeba

2023-11-28 17:37 UTC, tomtomklima commented on src/Application/migrations/20231127201235_add_printed_handbook_switch.php
> +        $tableUser->addColumn('printed_handbook', 'string', ['null' => true]);
lepší použít typ 'boolean'

2023-11-28 17:37 UTC, tomtomklima commented on src/Application/migrations/20231127201235_add_printed_handbook_switch.php
> +final class AddPrintedHandbookSwitch extends AbstractMigration
spojit obě dvě migrace dohromady prosím

2023-11-28 17:37 UTC, tomtomklima commented on src/Event/EventType/Obrok/EventTypeObrok.php
> +        $ca->psychicalHealth = true;
není třeba, už je povolené

2023-11-28 17:37 UTC, tomtomklima commented on src/Event/EventType/Obrok/EventTypeObrok.php
> +        $ca->psychicalHealth = true;
není třeba, už je povolené

2023-11-28 17:37 UTC, tomtomklima commented on src/Event/EventType/Obrok/EventTypeObrok.php
>          return $ca;
přidat prosím i pro IST

2023-11-28 17:37 UTC, tomtomklima commented on src/Participant/Participant.php
> + * @property string|null            $printedHandbook
změnit na boolean

2023-11-28 17:37 UTC, tomtomklima commented on src/Participant/ParticipantService.php
> +        $p->printedHandbook = $params['printedHandbook'] ?? null;
convert na boolean

2023-11-28 17:37 UTC, tomtomklima commented on src/Templates/cs.yaml
> +    issues-placeholder: "alergie, zdravotní omezení"
pro SK též (stačí tam plácnout CZ překlad (:, ale aby tam něco bylo)

2023-11-28 17:37 UTC, tomtomklima commented on src/Templates/translatable/widgets/details.twig
> +    {% trans %}detail.printedHandbook{% endtrans %}:<b>{{ person.getPrintedHandbook ?? 'no' }}</b><br/>
vypsat ano/ne a pomocí překladů přeložit prosím

2023-11-28 19:07 UTC, paaton commented on src/Event/EventType/Obrok/EventTypeObrok.php
> +        $ca->psychicalHealth = true;
medicaments jsem dal v ca default false

2023-11-29 14:04 UTC, tomtomklima commented on src/Templates/translatable/widgets/details.twig
> +    {% trans %}detail.printedHandbook{% endtrans %}:<b>
přidat mezeru na dvojtečku

2023-11-29 14:04 UTC, tomtomklima commented on src/Templates/translatable/widgets/changeDetails.twig
> +         />
vyhodit lomítko navíc - jde tam, ale jinde není

2023-11-29 15:12 UTC, paaton commented on composer.lock
omyl, jen ho nedokážu už vrátit asi, vyřešíme v mergi?

2023-11-29 15:17 UTC, merged